"""Clinical report generation — richer formatting with confidence bar."""

import logging
from datetime import datetime
from typing import Any, Dict

logger = logging.getLogger(__name__)


def _confidence_bar(score: float, width: int = 20) -> str:
    filled = int(score * width)
    bar = "█" * filled + "░" * (width - filled)
    return f"`{bar}` {score:.1%}"


def _risk_badge(tumor_type: str) -> str:
    if "HGG" in tumor_type:
        return "🔴 **HIGH RISK** — Immediate specialist referral recommended"
    if "LGG" in tumor_type:
        return "🟡 **MODERATE RISK** — Clinical follow-up advised"
    return "🟢 **NO TUMOR DETECTED** — Routine monitoring suggested"


def generate_report(prediction_dict: Dict[str, Any]) -> str:
    logger.info("Generating clinical report...")
    try:
        now          = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
        tumor_type   = prediction_dict.get("tumor_type", "Unknown")
        confidence   = prediction_dict.get("confidence", 0.0)
        volume       = prediction_dict.get("volume_voxels", 0)
        detected     = prediction_dict.get("tumor_detected", False)

        conf_bar = _confidence_bar(confidence)
        risk     = _risk_badge(tumor_type)

        # Estimate volume in mm³ (approximate: 1 voxel ≈ 1 mm³ at 1mm iso)
        vol_mm3 = volume * 1.0

        report = f"""
# 🧠 Clinical Brain Tumor Analysis Report

---

| Field | Value |
|---|---|
| **Date** | {now} |
| **AI Model** | MONAI 3D UNet v1.0 |
| **Processing** | Full-pipeline (4-modality MRI) |

---

## 🔬 Primary Findings

### Classification
**{tumor_type}**

{risk}

### Confidence Score
{conf_bar}

### Tumor Volume
- **Voxel Count:** `{volume:,}` voxels
- **Estimated Volume:** `{vol_mm3:,.1f} mm³`
- **Tumor Detected:** {'✅ Yes' if detected else '❌ No'}

---

## 📋 Interpretation Guide

| Grade | Criteria | Action |
|---|---|---|
| HGG (High-Grade) | > {500:,} voxels | Urgent referral |
| LGG (Low-Grade)  | ≤ {500:,} voxels | Clinical review |
| No Tumor         | 0 voxels         | Monitoring |

---

## ⚕️ Clinical Disclaimer

> This report is generated by an **automated AI system** and is intended
> for **research and educational purposes only**.
> It must **not** be used as a substitute for professional medical advice,
> diagnosis, or treatment. All findings should be reviewed by a qualified
> radiologist or neurosurgeon.

---
_Generated by Brain Tumor AI · {now}_
""".strip()

        logger.info("Report generated.")
        return report

    except Exception as e:
        logger.error(f"Report error: {e}")
        return f"## ⚠️ Report generation failed\n\n`{e}`"
